# .github/workflows/release.yml
name: Release Please & Build

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

  build-windows:
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build & package (Windows)
        run: pnpm build:win
        # 如需代码签名，取消下面两行并配置对应 secret
        # env:
        #   CSC_LINK: ${{ secrets.WIN_CERT_BASE64 }}
        #   CSC_KEY_PASSWORD: ${{ secrets.WIN_CERT_PASSWORD }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release-please.outputs.tag_name }}
          files: |
            dist/xiaosheng-*-setup.exe
            dist/xiaosheng-*-setup.exe.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
