name: Build and Upload Release

on:
  release:
    types: [published]

jobs:
  build-release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js and pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build:win

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          # 使用通配符自动查找并上传所有安装包相关文件
          files: |
            release/xiaosheng-*-setup.exe
            release/xiaosheng-*-setup.exe.blockmap
